/**
 * The dynamic version that is  automatically generated by the build process.
 * @module version
 */
export var VERSION = '0.1.36'
export var BUILD = '2021-07-22T09:39:52-07:00'
export var GIT_COMMIT_ID = '93f5af6'
export var GIT_BRANCH = 'main'
