/**
 * The dynmamic version that is  automatically generated by the build process.
 * @module version
 */
export var VERSION = '0.1.26'
export var BUILD = '2021-07-04T14:58:48-07:00'
export var GIT_COMMIT_ID = '162c2b0'
export var GIT_BRANCH = '20210703-jsdoc'
